### ISSUE TITLE
User login audits 

### ISSUE THREAD

**Issue by assettracking** [scottbrady91/Blog-Example-Classes#1]
Scott, this is far above the best sample for multi tenancy, :+1:  so thanks for sharing this, and also I wanted to ask for some understanding help 

Does this mean _if I have a SAAS app, and I have two companies registeresd COMPxyz and COMPabc_ - will this multi-tenant id isolate the members of the two groups?   i.e. _managers_ role from a _group_/COMPxyz can only see employees in COMPxyz but not employess in COMPabc - 
I saw this code below, but the blog did not list usage snippets on how to check inside the action for the tenants, if I need to use/check the `tenantID`in the `usermanager()` show me snippet on how to check

```
var context = new ApplicationUserDbContext<ApplicationUser>("DefaultConnection");
var userStore = new ApplicationUserStore<ApplicationUser>(context) { TenantId = 1 };
var userManager = new UserManager<ApplicationUser, string>(userStore);
```

Can you tell me how/(where in the code, is login form the best place?) to watch/log/audit the login attempts from a user, for e.g. we want to know if there is a brute force attack and someone is trying to log-in. I want to lock the account, if there are 5 bad logins within 5 mins.

thanks

**Comment by scottbrady91** [comment]
Yes, that's correct. If you use a User Manager and set a Tenant Id, you will only receive results for that Tenant Id. You can use ASP.NET Identity in exactly the same way as usual, just don't forget to set that Tenant Id first.

User lockout is also set at a User Manager level using the `UserLockoutEnabledByDefault`, `MaxFailedAccessAttemptsBeforeLockout` and `DefaultAccountLockoutTimeSpan` properties.
