### ISSUE TITLE
User Subscription in a SAAS app 

### ISSUE THREAD

**Issue by smartmeter** [scottbrady91/Blog-Example-Classes#2]
Hi Scott, kudos, very nice blog article, a missing :key: in multi tenant solution,
1. If we have SAAS app, where users from 2 different organizations are logging in, and I have the same app instance serving/running and the tenant is fixed during the new dbContext, isnt it fixed to only one tenant per app instance.
2. It _was my impression_ IMHO, that in the same app instance could serve many organizations (SAAS); and, I would leverage/fetch the users `tenantID`from an extended Identity userID/principal from the session to save/preform data operations. Am I wrong here, can you help with a modification. I believe the key to making this work, would be letting the user select a Tenant(or Organization, during registration).
3. Lastly, I am using the identity with a roles approach, will you solution still work, I ask because you mentioned claims in your original blog. What would I need to make it work with roles?

thanks

**Comment by scottbrady91** [comment]
1. You can change the tenant Id at any time during a dbcontext's lifetime. Also, you can have any number dbcontexts around at any time, so changing the tenant Id a dbcontext is currently serving can be avoided by simply newing up another dbcontext.
2. You can set the tenant Id anywhere you like, for example the user could select it or it could be hardcoded at the host level. It really is up to you and has no bearing on the underlying repositories.
3. A role is a type of claim, ASP.NET Identity just gives it its own table in the database, which confuses things, I know. But yes, it will work, no changes necessary

Hope that helps
